sudo: false

language:
  - python

python:
  - 3.7

install:
  - pip install pytest
  - pip install ./"Code Library"/venv/requirements.txt

script:
  - pytest --verbose ./"Code Library"/venv/main.py

notifications:
  email: false