# Generated by Django 3.0.4 on 2020-03-29 17:51

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
