# Generated by Django 2.1.14 on 2020-03-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterquality',
            name='analyst_initials',
        ),
        migrations.RemoveField(
            model_name='waterquality',
            name='enterer_intials',
        ),
        migrations.RemoveField(
            model_name='waterquality',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='waterquality',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='waterquality',
            name='pval_one',
        ),
        migrations.RemoveField(
            model_name='waterquality',
            name='pval_three',
        ),
        migrations.RemoveField(
            model_name='waterquality',
            name='pval_two',
        ),
    ]
