# Generated by Django 3.0.3 on 2020-02-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('river_name', models.CharField(max_length=100)),
                ('enteree', models.CharField(max_length=100)),
            ],
        ),
    ]
