# Generated by Django 2.1.14 on 2020-03-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('jar_number', models.IntegerField()),
                ('collection_time', models.DateTimeField()),
                ('pval_one', models.FloatField()),
                ('pval_two', models.FloatField()),
                ('pval_three', models.FloatField()),
                ('collector_initials', models.CharField(max_length=3)),
                ('analyst_initials', models.CharField(max_length=3)),
                ('enterer_intials', models.CharField(max_length=3)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pressure_difference', models.FloatField()),
                ('pressure_absolute', models.FloatField()),
                ('temperature', models.FloatField()),
                ('water_level', models.FloatField()),
                ('pressure_baro', models.FloatField()),
                ('reference_water_level', models.FloatField()),
                ('water_density', models.FloatField()),
            ],
        ),
    ]
